spring:
  jpa:
    open-in-view: false #check_what_is_it
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/testjwt
    username: root
    password: 15w04i19t94f
    initialization-mode: always