spring:
  profiles: dev
  h2:
    console:
      enabled: true
server:
  port: 8081

my:
  property: DEV

feedback:
  service:
    port: 8801
    host: 10.143.143.100

---

spring:
  profiles: prod

my:
  property: PROD

asdf:
  asdfasdf: asdg

