spring:
  profiles: dev
  h2:
    console:
      enabled: true
server:
  port: 8081

my:
  property: DEV

feedback:
  service:
    port: 8801
    host: 10.143.143.100

---

spring:
  profiles: prod
  jpa:
    open-in-view: false #check_what_is_it
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 15w04i19t94f
    initialization-mode: always
#    url: jdbc:postgresql://localhost:5432/test
#    username: postgres
#    password: 15w04i19t94F!

my:
  property: PROD

asdf:
  asdfasdf: asdg

#spring.datasource.initialization-mode=always
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

management:
  server:
    port: 5000
  endpoints:
    web:
      exposure:
        include: httptrace