spring:
  profiles: dev
  h2:
    console:
      enabled: true
server:
  port: 8081

my:
  property: DEV

feedback:
  service:
    port: 8801
    host: 10.143.143.100

---

spring:
  profiles: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 15w04i19t94f
    initialization-mode: always
#    url: jdbc:postgresql://localhost:5432/test
#    username: postgres
#    password: 15w04i19t94F!
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true

my:
  property: PROD

asdf:
  asdfasdf: asdg

#spring.datasource.initialization-mode=always